apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: catalog-depl
spec:
  selector:
    matchLabels:
      app: catalog
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalogservice
        image: pratikdas/catalogsvc:v1
        ports:
        - containerPort: 8080
        env:
        - name: api.pricingBaseURL
          value: http://pricing-service:8082 
        - name: api.inventoryBaseURL
          value: http://inventory-service:8081   
        - name: api.inventoryBaseURL1
          value: http://inventory-service:8081       
---  
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: NodePort
  selector:
    app: catalog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001