apiVersion: v1  
kind: Service  
metadata:  
  name: usersignup-service  
  labels:  
    app: usersignup-service  
spec:  
  ports:  
    - name: http  
      port: 8000  
  selector:  
    app: usersignup-service  
---  

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: usersignup-svc-deployment
spec:
  selector:
    matchLabels:
      app: usersignup
  replicas: 3
  template:
    metadata:
      labels:
        app: usersignup
    spec:
      containers:
      - name: usersignupservice
        image: usersignupservice:1.0
        ports:
        - containerPort: 8080
        livenessProbe:  
            httpGet:  
              path: /actuator/health/liveness  
              port: 8000  
            initialDelaySeconds: 5  
            periodSeconds: 5